# do not touch this line
configVersion: 2

description: testing unity web games
keywords: ''
name: unityTest

sensors:
  - gyroscope

dataTypes:
  ipAddress:
    websiteIP: string
    gameIP: string

screens:
  - - webPageURL
  - - gameIP

widgets:
  webPageURL:
    display: label
    type: ipAddress
    key: websiteIP
    label: Website URL
  gameIP:
    display: label
    type: ipAddress
    key: gameIP
    label: Game IP